# Dockerfile.dev

FROM node:22

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    openssl \
    bash \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dulu file buat install dependencies
COPY package*.json ./

COPY . .
# Install dependencies dulu → cache layer
RUN npm install

# Prisma generate (harus setelah schema.prisma tersedia)
RUN npx prisma generate

EXPOSE 5000
CMD ["npm", "run", "dev"]
